### ISSUE TITLE
AsyncTCP.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by ldijkman** [G6EJD/ESP-SMART-Thermostat#1]
Hello

downloaded the zip as described and istalled lib from zip
but get an error 
and i see no AsyncTCP.h in the library directory

can you help me?
 i am impressed with your code
can learn a lot from it

###############
ok later i read his 
For ESP32 it requires AsyncTCP to work To use this library you might need to have the latest git versions of ESP32 Arduino Core
https://github.com/espressif/arduino-esp32

hmmmm i do not know, cannot get it working
maybe this https://github.com/me-no-dev/AsyncTCP
yes now its programming
############################

luberth
http://Arduino.TK
Art  tft touch Thermostat needs an web intrface ;-)

#include "ESPAsyncWebServer.h"         // https://github.com/me-no-dev/ESPAsyncWebServer/tree/63b5303880023f17e1bca517ac593d8a33955e94

In file included from /home/pi/Downloads/ESP-SMART-Thermostat-main/ESP32_Thermostat_v1/ESP32_Thermostat_v1.ino:22:0:
/home/pi/Arduino/libraries/ESPAsyncWebServer/src/ESPAsyncWebServer.h:33:22: fatal error: AsyncTCP.h: No such file or directory
compilation terminated.

**Comment by ldijkman** [comment]
For ESP32 it requires AsyncTCP to work To use this library you might need to have the latest git versions of ESP32 Arduino Core

**Comment by G6EJD** [comment]
That’s interesting as Espressif says it’s included in the latest ESP32 core, which one are you using, I didn’t download that particular library. Have downloaded it yet?

**Comment by ldijkman** [comment]
cool
https://github.com/me-no-dev/AsyncTCP
did it
![2020-12-25-225202_1360x768_scrot](https://user-images.githubusercontent.com/45427770/103142483-025ca780-4704-11eb-963a-cdcd6b266431.png)

**Comment by ldijkman** [comment]
> That’s interesting as Espressif says it’s included in the latest ESP32 core, which one are you using, I didn’t download that particular library. Have you downloaded it yet?

sorry i do not understand everything with that core thing
is that for board manager or library
i treid several things
restarted several times after changes
but i think https://github.com/me-no-dev/AsyncTCP did tit

**Comment by ldijkman** [comment]
like your variable write read
must look into that part for my thermostat art
http://arduino.tk

greet luberth from the netherklands

**Comment by ldijkman** [comment]
connected sda scl wron this is better

![2020-12-25-230704_1360x768_scrot](https://user-images.githubusercontent.com/45427770/103142599-f8d43f00-4705-11eb-8ab4-9cea5b4b33eb.png)

**Comment by ldijkman** [comment]
impressive what you have made
compliments

**Comment by G6EJD** [comment]
For ESP8266 it requires ESPAsyncTCP To use this library you might need to have the latest git versions of ESP8266 Arduino Core

For ESP32 it requires AsyncTCP to work To use this library you might need to have the latest git versions of ESP32 Arduino Core

**Comment by MasterCATZ** [comment]
using wemos D1 mini 

it halts booting once connected to wifi and does not seem to start anything , unsure if it even tries syncing the time ?

8:20:14.166 -> StartESP8266_Thermostat_v1.ino
18:20:14.166 -> Startnleashed
18:20:14.199 -> ..............................
18:20:18.013 -> WiFi connected at: 192.168.2.90

it shows up on my router as an esp not using Thermostat device name 

any idea's i am unsure if it is from me not loading Async libraries correctly  I just downloaded the git zips and loaded them that way ?

**Comment by G6EJD** [comment]
Dudu you try connecting to http://192.168.2.90/
