### ISSUE TITLE
Replacing BME280 with HTU21

### ISSUE THREAD

**Issue by lex007112** [G6EJD/ESP-SMART-Thermostat#2]
Hello, do not tell me what needs to be changed in the sketch so that HTU21 works instead of BME280, the second day I can not solve this problem, since I am just starting the first steps in mastering programming. I would be very grateful for your help.

**Comment by G6EJD** [comment]
Try this version: https://github.com/G6EJD/ESP-SMART-Thermostat

It should work, but you might have to tell me what device you have and what library works with it.

**Comment by lex007112** [comment]
> Try this version: https://github.com/G6EJD/ESP-SMART-Thermostat
> 
> It should work, but you might have to tell me what device you have and what library works with it.

Works, but does not read the temperature from the sensor. My sensor library: https://github.com/adafruit/Adafruit_HTU21DF_Library.git . Board: esp32 wroom 32d

**Comment by G6EJD** [comment]
What pins are you using for i2c? What board type do you select? Have you had the sensor running efore?

**Comment by lex007112** [comment]
![github1](https://user-images.githubusercontent.com/57561753/103197275-722e8600-48ee-11eb-897e-3bc785200044.png)
![github2](https://user-images.githubusercontent.com/57561753/103197404-a013ca80-48ee-11eb-94bb-5d3a9cede143.jpg)
![image](https://user-images.githubusercontent.com/57561753/103197477-c46fa700-48ee-11eb-854b-2fef46f35489.png)
![github3](https://user-images.githubusercontent.com/57561753/103197770-5bd4fa00-48ef-11eb-9ef4-8eb0a053ca1f.jpg)

Working sensor, checked.
VCC=>3.3v
GND=>GND
SCL=>22
SDA=>21

**Comment by lex007112** [comment]
> ![github1](https://user-images.githubusercontent.com/57561753/103197275-722e8600-48ee-11eb-897e-3bc785200044.png)
> ![github2](https://user-images.githubusercontent.com/57561753/103197404-a013ca80-48ee-11eb-94bb-5d3a9cede143.jpg)
> ![image](https://user-images.githubusercontent.com/57561753/103197477-c46fa700-48ee-11eb-854b-2fef46f35489.png)
> ![github3](https://user-images.githubusercontent.com/57561753/103197770-5bd4fa00-48ef-11eb-9ef4-8eb0a053ca1f.jpg)
> 
> 
![image](https://user-images.githubusercontent.com/57561753/103198392-e23e0b80-48f0-11eb-9eb5-b84e8ba2a640.png)

Working sensor, checked.
> VCC=>3.3v
> GND=>GND
> SCL=>22
> SDA=>21

**Comment by lex007112** [comment]
![image](https://user-images.githubusercontent.com/57561753/103198601-64c6cb00-48f1-11eb-88fb-9b8503d81084.png)

**Comment by G6EJD** [comment]
You did see that I created a new code for the sht21? See the code versions, as all references to the bme280 are removed but your serial port shows it being there?

**Comment by lex007112** [comment]
![image](https://user-images.githubusercontent.com/57561753/103210213-be3cf300-490d-11eb-8801-61824858608e.png)
Thank you very much, you are a Human with a capital letter !!! Didn't really notice the new code. Now I will try to screw up the TFT screen if possible. Thanks again for your hard work !!!

**Comment by lex007112** [comment]
> ![image](https://user-images.githubusercontent.com/57561753/103210213-be3cf300-490d-11eb-8801-61824858608e.png)
> Thank you very much, you are a Human with a capital letter !!! Didn't really notice the new code. Now I will try to screw up the TFT screen  ili9341 if possible. Thanks again for your hard work !!!

**Comment by G6EJD** [comment]
Happy to help
