### ISSUE TITLE
Therm Temp Set

### ISSUE THREAD

**Issue by florin03** [G6EJD/ESP-SMART-Thermostat#3]
Hello,
Manual heating over-ride & Manual Override Temperature it is not stored, this means if you lose power to esp it will revert to default 21 degrees (initial temp that was added in Arduino sketch).
Thanx

**Comment by G6EJD** [comment]
That’s correct by design, I made it a manual override until the next scheduled timed event.

**Comment by G6EJD** [comment]
If there’s a power cut and the timers are off there will be no thermostat action ie off

**Comment by florin03** [comment]
If you designed this for heating system (for a house,apartment.....) manual set temp should be stored, also the temp should be received from external temp sensor (maybe another esp with an battery and temp sensor, screen...) to be truly wifi thermostat.

**Comment by G6EJD** [comment]
Please rewrite the code and propose the amendments here for inclusion, this is how GitHub works.
