### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by Anoxym** [G6EJD/ESP-SMART-Thermostat#4]
Hi,

a very good project ! Is it possible to add these features :

- Support for DHT22
- Notifications (like PushOver or Mail) when the threshold is reached like :
      * Alert, humidity is under 30% | Alert, humidity is above 70%
      * Alert, temperature is under 20°C| Alert, temperature is above 40°C

This would be wonderful

Thanks a lot

**Comment by G6EJD** [comment]
Yes but it all takes time and effort that I don’t have to spare as I have to work, this is just an example project for people to build upon. I give out these examples for people to use as a foundation to add their own features. It’s not a software issue, sorry.
