### ISSUE TITLE
Time&Date stamp on the status page

### ISSUE THREAD

**Issue by mcsabi** [G6EJD/ESP-SMART-Thermostat#5]
Excellent project, thank you for it! 
Would it be possible to add a time & date stamp on the status page so that we know what is the esp8266 time setup?
Thank you

**Comment by G6EJD** [comment]
There are two variables Time_str and Date_str that can simply be added to the home page in html location of your choice:
“<p>“ + Time_str + “ “ + Date_str + </p>

**Comment by mcsabi** [comment]
thank you!!! Appreciate you quick help!
