### ISSUE TITLE
MQTT feature rquest

### ISSUE THREAD

**Issue by mcsabi** [G6EJD/ESP-SMART-Thermostat#6]
First of all thank you for code!
My plan is to use this thermostat as a scheduler and to measure the temperature at the given room. I already have tasmotized ESP8266 connected to the heater. Intention is to send an MQTT message when the relay turns on or off based on schedule/temperature (no relay needed physically) and the remote tasmota devise would switch its relay on/off accordingly.  An example of an MQTT message would be "cmnd/heater/POWER1 1" (to turn on the remote relay)
Would it be a lot of work to implement it? Unfortunately I am not a programmer :(
Thank you

**Comment by G6EJD** [comment]
Without researching the changes:
You’d need to include the MQTT library
At the point in the code where the relay is turned on/off send the command cmnd/heater/POWER1 1
Or
cmnd/heater/POWER1 0

It seems straightforward. I don’t have the time to do that at the moment got too much work on.

**Comment by G6EJD** [comment]
#include <PubSubClient.h>
const char* mqtt_server = "YOUR_MQTT_BROKER_IP_ADDRESS";
PubSubClient client(espClient);

in the setup after the WiFi start:
client.setServer(mqtt_server, 1883);


At the point of relay on:
client.publish("cmd/heater1/POWER1”, ”1”);
Repeat for relay off with a 0 as the parameter.

**Comment by G6EJD** [comment]
So about 4 lines of code

**Comment by mcsabi** [comment]
Thank you, will try to modify add the lines! Appreciate your quick response and resolution!
