### ISSUE TITLE
ESP- 12F ESP8266

### ISSUE THREAD

**Issue by MasterCATZ** [G6EJD/ESP-SMART-Thermostat#7]
is it possible to get this ESP- 12F ESP8266 to control relays ? I can not seem to find a pin that this sketch will accept for 

#define RelayPIN        D1             // Define the Relay Control pin

Arduino: 1.8.14 Hourly Build 2021/04/08 03:25 (Linux), Board: "DOIT ESP-Mx DevKit (ESP8285), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 1MB (FS:64KB OTA:~470KB), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

/SnapRaidArray/DATA/git/ESP-SMART-Thermostat/ESP8266_Thermostat_v1/ESP8266_Thermostat_v1.ino: In function 'void ActuateHeating(bool)':
ESP8266_Thermostat_v1:43:25: error: 'D1' was not declared in this scope; did you mean 'y1'?
   43 | #define RelayPIN        D1             // Define the Relay Control pin
      |                         ^~
/SnapRaidArray/DATA/git/ESP-SMART-Thermostat/ESP8266_Thermostat_v1/ESP8266_Thermostat_v1.ino:503:11: note: in expansion of macro 'RelayPIN'
  503 |   pinMode(RelayPIN, OUTPUT);
      |           ^~~~~~~~
/SnapRaidArray/DATA/git/ESP-SMART-Thermostat/ESP8266_Thermostat_v1/ESP8266_Thermostat_v1.ino: In function 'void StartSensor()':
ESP8266_Thermostat_v1:769:14: error: 'D4' was not declared in this scope
  769 |   Wire.begin(D4, D3);                              // Default SDA and SCL pins
      |              ^~
ESP8266_Thermostat_v1:769:18: error: 'D3' was not declared in this scope
  769 |   Wire.begin(D4, D3);                              // Default SDA and SCL pins
      |                  ^~
exit status 1
'D1' was not declared in this scope; did you mean 'y1'?

**Comment by G6EJD** [comment]
No the code was for the Wemos D1 mini which has a pin definition of D1 for the board your using you need to use PIN numbers eg just 3 or 4 or whatever
