### ISSUE TITLE
Firefox prevented this page from automatically reloading

### ISSUE THREAD

**Issue by FrankHovis** [G6EJD/ESP-SMART-Thermostat#8]
Firefox doesn't like whatever is happening with the webpages, it constantly complains that its prevented the page reloading.

**Comment by G6EJD** [comment]
Well if you run the resultant HTML through the W3C html checker it gets a 100% compatibility score, I spent a long time getting that right, what happens if you use another browser?
This I sent really a code problem It’s a browser issue frequently encountered across the internet.
